build:
	g++ -std=c++0x includes/database.cpp includes/html.cpp process/user.cpp drivers/index.cpp -o ../www/index.html -lmysqlcppconn -lcgicc
	g++ -std=c++0x includes/database.cpp includes/html.cpp process/user.cpp drivers/post.cpp -o ../www/post.html -lmysqlcppconn -lcgicc
	g++-4.9 -std=c++0x includes/database.cpp includes/profile.cpp includes/html.cpp process/user.cpp process/question.cpp process/answer.cpp process/comment.cpp process/vote.cpp drivers/question.cpp -o ../www/question.html -lmysqlcppconn -lcgicc
	g++ -std=c++0x includes/database.cpp includes/html.cpp process/user.cpp process/browse.cpp drivers/browse.cpp -o ../www/browse.html -lmysqlcppconn -lcgicc
	g++ -std=c++0x includes/database.cpp includes/html.cpp process/user.cpp process/report.cpp drivers/report.cpp -o ../www/report.html -lmysqlcppconn -lcgicc
	g++ -std=c++0x includes/database.cpp includes/md5.cpp includes/html.cpp process/user.cpp drivers/signup.cpp -o ../www/signup.html -lmysqlcppconn -lcgicc
	g++ -std=c++0x includes/database.cpp includes/md5.cpp includes/html.cpp process/user.cpp drivers/login.cpp -o ../www/login.html -lmysqlcppconn -lcgicc
	g++ -std=c++0x includes/database.cpp process/user.cpp includes/html.cpp drivers/allquestions.cpp -o ../www/allquestions.html -lmysqlcppconn -lcgicc
	g++ -std=c++0x includes/database.cpp process/user.cpp includes/html.cpp process/search.cpp drivers/search.cpp -o ../www/search.html -lmysqlcppconn -lcgicc
	g++ -std=c++0x includes/database.cpp includes/html.cpp includes/md5.cpp process/report.cpp process/user.cpp drivers/profile.cpp -o ../www/profile.html -lmysqlcppconn -lcgicc
	g++ -std=c++0x includes/database.cpp includes/html.cpp process/user.cpp drivers/editprofile.cpp -o ../www/editprofile.html -lmysqlcppconn -lcgicc
	g++ -std=c++0x includes/database.cpp includes/json.cpp includes/html.cpp process/user.cpp api/vote.cpp -o ../www/api/vote.html -lmysqlcppconn -lcgicc
	g++ -std=c++0x includes/database.cpp includes/html.cpp includes/md5.cpp process/user.cpp drivers/editpassword.cpp -o ../www/editpassword.html -lmysqlcppconn -lcgicc
	g++ -std=c++0x includes/database.cpp includes/html.cpp process/user.cpp drivers/accdeactivate.cpp -o ../www/accdeactivate.html -lmysqlcppconn -lcgicc
	g++ -std=c++0x includes/database.cpp includes/html.cpp process/user.cpp drivers/editcontent.cpp -o ../www/editcontent.html -lmysqlcppconn -lcgicc
	g++ -std=c++0x includes/database.cpp includes/html.cpp process/user.cpp drivers/adminedit.cpp -o ../www/adminedit.html -lmysqlcppconn -lcgicc
	g++ -std=c++0x includes/database.cpp includes/html.cpp process/user.cpp drivers/admindeactivate.cpp -o ../www/admindeactivate.html -lmysqlcppconn -lcgicc
	g++ -std=c++0x includes/database.cpp includes/html.cpp process/user.cpp process/report.cpp drivers/viewAllUser.cpp -o ../www/viewalluser.html -lmysqlcppconn -lcgicc
	g++ -std=c++0x includes/database.cpp includes/html.cpp process/user.cpp drivers/changeRep.cpp -o ../www/changerep.html -lmysqlcppconn -lcgicc
	g++ -std=c++0x includes/database.cpp includes/html.cpp process/user.cpp drivers/changeptssys.cpp -o ../www/changeptssys.html -lmysqlcppconn -lcgicc
	g++ -std=c++0x includes/database.cpp includes/html.cpp process/user.cpp drivers/processptschange.cpp -o ../www/processptschange.html -lmysqlcppconn -lcgicc
current:
	g++ -std=c++0x includes/database.cpp includes/html.cpp process/search.cpp drivers/search.cpp -o ../www/search.html -lmysqlcppconn -lcgicc
