build:
	g++ -std=c++0x includes/database.cpp includes/html.cpp drivers/index.cpp -o ../www/index.html -lmysqlcppconn -lcgicc
	g++ -std=c++0x includes/database.cpp includes/html.cpp process/post.cpp drivers/post.cpp -o ../www/post/index.html -lmysqlcppconn -lcgicc
